# Generated by Django 4.1.7 on 2023-05-15 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_product_description_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.ManyToManyField(to='seller.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
