# Generated by Django 4.1.7 on 2023-05-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_seller_info_user_cust_info'),
        ('ordering', '0005_remove_order_seller_order_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.cust_info'),
        ),
    ]
